// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.3
// source: error.proto

package error_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	ErrId   *ErrID   `protobuf:"bytes,2,opt,name=err_id,json=errId,proto3" json:"err_id,omitempty"`
	ErrCall *ErrCall `protobuf:"bytes,3,opt,name=err_call,json=errCall,proto3" json:"err_call,omitempty"`
	ErrLost *ErrLost `protobuf:"bytes,4,opt,name=err_lost,json=errLost,proto3" json:"err_lost,omitempty"`
	ErrWait *ErrWait `protobuf:"bytes,5,opt,name=err_wait,json=errWait,proto3" json:"err_wait,omitempty"`
	ErrSdp  *ErrSdp  `protobuf:"bytes,6,opt,name=err_sdp,json=errSdp,proto3" json:"err_sdp,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_error_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_error_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_error_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetErrId() *ErrID {
	if x != nil {
		return x.ErrId
	}
	return nil
}

func (x *Error) GetErrCall() *ErrCall {
	if x != nil {
		return x.ErrCall
	}
	return nil
}

func (x *Error) GetErrLost() *ErrLost {
	if x != nil {
		return x.ErrLost
	}
	return nil
}

func (x *Error) GetErrWait() *ErrWait {
	if x != nil {
		return x.ErrWait
	}
	return nil
}

func (x *Error) GetErrSdp() *ErrSdp {
	if x != nil {
		return x.ErrSdp
	}
	return nil
}

type ErrID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID int32 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *ErrID) Reset() {
	*x = ErrID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_error_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrID) ProtoMessage() {}

func (x *ErrID) ProtoReflect() protoreflect.Message {
	mi := &file_error_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrID.ProtoReflect.Descriptor instead.
func (*ErrID) Descriptor() ([]byte, []int) {
	return file_error_proto_rawDescGZIP(), []int{1}
}

func (x *ErrID) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

type ErrCall struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ErrCall) Reset() {
	*x = ErrCall{}
	if protoimpl.UnsafeEnabled {
		mi := &file_error_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrCall) ProtoMessage() {}

func (x *ErrCall) ProtoReflect() protoreflect.Message {
	mi := &file_error_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrCall.ProtoReflect.Descriptor instead.
func (*ErrCall) Descriptor() ([]byte, []int) {
	return file_error_proto_rawDescGZIP(), []int{2}
}

type ErrLost struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID int32 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *ErrLost) Reset() {
	*x = ErrLost{}
	if protoimpl.UnsafeEnabled {
		mi := &file_error_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrLost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrLost) ProtoMessage() {}

func (x *ErrLost) ProtoReflect() protoreflect.Message {
	mi := &file_error_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrLost.ProtoReflect.Descriptor instead.
func (*ErrLost) Descriptor() ([]byte, []int) {
	return file_error_proto_rawDescGZIP(), []int{3}
}

func (x *ErrLost) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

type ErrWait struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ErrWait) Reset() {
	*x = ErrWait{}
	if protoimpl.UnsafeEnabled {
		mi := &file_error_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrWait) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrWait) ProtoMessage() {}

func (x *ErrWait) ProtoReflect() protoreflect.Message {
	mi := &file_error_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrWait.ProtoReflect.Descriptor instead.
func (*ErrWait) Descriptor() ([]byte, []int) {
	return file_error_proto_rawDescGZIP(), []int{4}
}

type ErrSdp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ErrSdp) Reset() {
	*x = ErrSdp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_error_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrSdp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrSdp) ProtoMessage() {}

func (x *ErrSdp) ProtoReflect() protoreflect.Message {
	mi := &file_error_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrSdp.ProtoReflect.Descriptor instead.
func (*ErrSdp) Descriptor() ([]byte, []int) {
	return file_error_proto_rawDescGZIP(), []int{5}
}

var File_error_proto protoreflect.FileDescriptor

var file_error_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd1, 0x01,
	0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x1d, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x06, 0x2e, 0x45, 0x72, 0x72, 0x49, 0x44, 0x52, 0x05, 0x65, 0x72, 0x72, 0x49, 0x64,
	0x12, 0x23, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x5f, 0x63, 0x61, 0x6c, 0x6c, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x08, 0x2e, 0x45, 0x72, 0x72, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x07, 0x65, 0x72,
	0x72, 0x43, 0x61, 0x6c, 0x6c, 0x12, 0x23, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x5f, 0x6c, 0x6f, 0x73,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x45, 0x72, 0x72, 0x4c, 0x6f, 0x73,
	0x74, 0x52, 0x07, 0x65, 0x72, 0x72, 0x4c, 0x6f, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x08, 0x65, 0x72,
	0x72, 0x5f, 0x77, 0x61, 0x69, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x45,
	0x72, 0x72, 0x57, 0x61, 0x69, 0x74, 0x52, 0x07, 0x65, 0x72, 0x72, 0x57, 0x61, 0x69, 0x74, 0x12,
	0x20, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x5f, 0x73, 0x64, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x07, 0x2e, 0x45, 0x72, 0x72, 0x53, 0x64, 0x70, 0x52, 0x06, 0x65, 0x72, 0x72, 0x53, 0x64,
	0x70, 0x22, 0x17, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x49, 0x44, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x44, 0x22, 0x09, 0x0a, 0x07, 0x45, 0x72,
	0x72, 0x43, 0x61, 0x6c, 0x6c, 0x22, 0x19, 0x0a, 0x07, 0x45, 0x72, 0x72, 0x4c, 0x6f, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x44,
	0x22, 0x09, 0x0a, 0x07, 0x45, 0x72, 0x72, 0x57, 0x61, 0x69, 0x74, 0x22, 0x08, 0x0a, 0x06, 0x45,
	0x72, 0x72, 0x53, 0x64, 0x70, 0x42, 0x1f, 0x5a, 0x1d, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x6d, 0x67, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x5f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_error_proto_rawDescOnce sync.Once
	file_error_proto_rawDescData = file_error_proto_rawDesc
)

func file_error_proto_rawDescGZIP() []byte {
	file_error_proto_rawDescOnce.Do(func() {
		file_error_proto_rawDescData = protoimpl.X.CompressGZIP(file_error_proto_rawDescData)
	})
	return file_error_proto_rawDescData
}

var file_error_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_error_proto_goTypes = []any{
	(*Error)(nil),   // 0: Error
	(*ErrID)(nil),   // 1: ErrID
	(*ErrCall)(nil), // 2: ErrCall
	(*ErrLost)(nil), // 3: ErrLost
	(*ErrWait)(nil), // 4: ErrWait
	(*ErrSdp)(nil),  // 5: ErrSdp
}
var file_error_proto_depIdxs = []int32{
	1, // 0: Error.err_id:type_name -> ErrID
	2, // 1: Error.err_call:type_name -> ErrCall
	3, // 2: Error.err_lost:type_name -> ErrLost
	4, // 3: Error.err_wait:type_name -> ErrWait
	5, // 4: Error.err_sdp:type_name -> ErrSdp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_error_proto_init() }
func file_error_proto_init() {
	if File_error_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_error_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_error_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ErrID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_error_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ErrCall); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_error_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ErrLost); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_error_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*ErrWait); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_error_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*ErrSdp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_error_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_error_proto_goTypes,
		DependencyIndexes: file_error_proto_depIdxs,
		MessageInfos:      file_error_proto_msgTypes,
	}.Build()
	File_error_proto = out.File
	file_error_proto_rawDesc = nil
	file_error_proto_goTypes = nil
	file_error_proto_depIdxs = nil
}
