// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.3
// source: return.proto

package return_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	error_pb "sessionmgr/proto/pkg/error_pb"
	ready_pb "sessionmgr/proto/pkg/ready_pb"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Return struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err                 *error_pb.Error      `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	CreateSessionReturn *ReturnCreateSession `protobuf:"bytes,2,opt,name=create_session_return,json=createSessionReturn,proto3" json:"create_session_return,omitempty"`
	OfferReturn         *ReturnOffer         `protobuf:"bytes,3,opt,name=offer_return,json=offerReturn,proto3" json:"offer_return,omitempty"`
	JoinSessionReturn   *ReturnJoinSession   `protobuf:"bytes,4,opt,name=join_session_return,json=joinSessionReturn,proto3" json:"join_session_return,omitempty"`
	AnswerReturn        *ReturnAnswer        `protobuf:"bytes,5,opt,name=answer_return,json=answerReturn,proto3" json:"answer_return,omitempty"`
	ConfirmAnswerReturn *ReturnConfirmAnswer `protobuf:"bytes,6,opt,name=confirm_answer_return,json=confirmAnswerReturn,proto3" json:"confirm_answer_return,omitempty"`
	SendReturn          *ReturnSend          `protobuf:"bytes,7,opt,name=send_return,json=sendReturn,proto3" json:"send_return,omitempty"`
	ReadyReturn         *ReturnReady         `protobuf:"bytes,8,opt,name=ready_return,json=readyReturn,proto3" json:"ready_return,omitempty"`
	DropSessionReturn   *ReturnDropSession   `protobuf:"bytes,9,opt,name=drop_session_return,json=dropSessionReturn,proto3" json:"drop_session_return,omitempty"`
	ReloadConfigReturn  *ReturnReloadConfig  `protobuf:"bytes,10,opt,name=reload_config_return,json=reloadConfigReturn,proto3" json:"reload_config_return,omitempty"`
	DiscardReturn       *ReturnDiscard       `protobuf:"bytes,11,opt,name=discard_return,json=discardReturn,proto3" json:"discard_return,omitempty"`
}

func (x *Return) Reset() {
	*x = Return{}
	if protoimpl.UnsafeEnabled {
		mi := &file_return_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Return) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Return) ProtoMessage() {}

func (x *Return) ProtoReflect() protoreflect.Message {
	mi := &file_return_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Return.ProtoReflect.Descriptor instead.
func (*Return) Descriptor() ([]byte, []int) {
	return file_return_proto_rawDescGZIP(), []int{0}
}

func (x *Return) GetErr() *error_pb.Error {
	if x != nil {
		return x.Err
	}
	return nil
}

func (x *Return) GetCreateSessionReturn() *ReturnCreateSession {
	if x != nil {
		return x.CreateSessionReturn
	}
	return nil
}

func (x *Return) GetOfferReturn() *ReturnOffer {
	if x != nil {
		return x.OfferReturn
	}
	return nil
}

func (x *Return) GetJoinSessionReturn() *ReturnJoinSession {
	if x != nil {
		return x.JoinSessionReturn
	}
	return nil
}

func (x *Return) GetAnswerReturn() *ReturnAnswer {
	if x != nil {
		return x.AnswerReturn
	}
	return nil
}

func (x *Return) GetConfirmAnswerReturn() *ReturnConfirmAnswer {
	if x != nil {
		return x.ConfirmAnswerReturn
	}
	return nil
}

func (x *Return) GetSendReturn() *ReturnSend {
	if x != nil {
		return x.SendReturn
	}
	return nil
}

func (x *Return) GetReadyReturn() *ReturnReady {
	if x != nil {
		return x.ReadyReturn
	}
	return nil
}

func (x *Return) GetDropSessionReturn() *ReturnDropSession {
	if x != nil {
		return x.DropSessionReturn
	}
	return nil
}

func (x *Return) GetReloadConfigReturn() *ReturnReloadConfig {
	if x != nil {
		return x.ReloadConfigReturn
	}
	return nil
}

func (x *Return) GetDiscardReturn() *ReturnDiscard {
	if x != nil {
		return x.DiscardReturn
	}
	return nil
}

type ReturnCreateSession struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReturnCreateSession) Reset() {
	*x = ReturnCreateSession{}
	if protoimpl.UnsafeEnabled {
		mi := &file_return_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReturnCreateSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnCreateSession) ProtoMessage() {}

func (x *ReturnCreateSession) ProtoReflect() protoreflect.Message {
	mi := &file_return_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnCreateSession.ProtoReflect.Descriptor instead.
func (*ReturnCreateSession) Descriptor() ([]byte, []int) {
	return file_return_proto_rawDescGZIP(), []int{1}
}

type ReturnOffer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OfferBase64 string `protobuf:"bytes,1,opt,name=offer_base64,json=offerBase64,proto3" json:"offer_base64,omitempty"`
}

func (x *ReturnOffer) Reset() {
	*x = ReturnOffer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_return_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReturnOffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnOffer) ProtoMessage() {}

func (x *ReturnOffer) ProtoReflect() protoreflect.Message {
	mi := &file_return_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnOffer.ProtoReflect.Descriptor instead.
func (*ReturnOffer) Descriptor() ([]byte, []int) {
	return file_return_proto_rawDescGZIP(), []int{2}
}

func (x *ReturnOffer) GetOfferBase64() string {
	if x != nil {
		return x.OfferBase64
	}
	return ""
}

type ReturnJoinSession struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReturnJoinSession) Reset() {
	*x = ReturnJoinSession{}
	if protoimpl.UnsafeEnabled {
		mi := &file_return_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReturnJoinSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnJoinSession) ProtoMessage() {}

func (x *ReturnJoinSession) ProtoReflect() protoreflect.Message {
	mi := &file_return_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnJoinSession.ProtoReflect.Descriptor instead.
func (*ReturnJoinSession) Descriptor() ([]byte, []int) {
	return file_return_proto_rawDescGZIP(), []int{3}
}

type ReturnAnswer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AnswerBase64 string `protobuf:"bytes,1,opt,name=answer_base64,json=answerBase64,proto3" json:"answer_base64,omitempty"`
}

func (x *ReturnAnswer) Reset() {
	*x = ReturnAnswer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_return_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReturnAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnAnswer) ProtoMessage() {}

func (x *ReturnAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_return_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnAnswer.ProtoReflect.Descriptor instead.
func (*ReturnAnswer) Descriptor() ([]byte, []int) {
	return file_return_proto_rawDescGZIP(), []int{4}
}

func (x *ReturnAnswer) GetAnswerBase64() string {
	if x != nil {
		return x.AnswerBase64
	}
	return ""
}

type ReturnConfirmAnswer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReturnConfirmAnswer) Reset() {
	*x = ReturnConfirmAnswer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_return_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReturnConfirmAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnConfirmAnswer) ProtoMessage() {}

func (x *ReturnConfirmAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_return_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnConfirmAnswer.ProtoReflect.Descriptor instead.
func (*ReturnConfirmAnswer) Descriptor() ([]byte, []int) {
	return file_return_proto_rawDescGZIP(), []int{5}
}

type ReturnSend struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReturnSend) Reset() {
	*x = ReturnSend{}
	if protoimpl.UnsafeEnabled {
		mi := &file_return_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReturnSend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnSend) ProtoMessage() {}

func (x *ReturnSend) ProtoReflect() protoreflect.Message {
	mi := &file_return_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnSend.ProtoReflect.Descriptor instead.
func (*ReturnSend) Descriptor() ([]byte, []int) {
	return file_return_proto_rawDescGZIP(), []int{6}
}

type ReturnReady struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReadyList []*ready_pb.Ready `protobuf:"bytes,1,rep,name=ready_list,json=readyList,proto3" json:"ready_list,omitempty"`
}

func (x *ReturnReady) Reset() {
	*x = ReturnReady{}
	if protoimpl.UnsafeEnabled {
		mi := &file_return_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReturnReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnReady) ProtoMessage() {}

func (x *ReturnReady) ProtoReflect() protoreflect.Message {
	mi := &file_return_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnReady.ProtoReflect.Descriptor instead.
func (*ReturnReady) Descriptor() ([]byte, []int) {
	return file_return_proto_rawDescGZIP(), []int{7}
}

func (x *ReturnReady) GetReadyList() []*ready_pb.Ready {
	if x != nil {
		return x.ReadyList
	}
	return nil
}

type ReturnDropSession struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReturnDropSession) Reset() {
	*x = ReturnDropSession{}
	if protoimpl.UnsafeEnabled {
		mi := &file_return_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReturnDropSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnDropSession) ProtoMessage() {}

func (x *ReturnDropSession) ProtoReflect() protoreflect.Message {
	mi := &file_return_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnDropSession.ProtoReflect.Descriptor instead.
func (*ReturnDropSession) Descriptor() ([]byte, []int) {
	return file_return_proto_rawDescGZIP(), []int{8}
}

type ReturnReloadConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReturnReloadConfig) Reset() {
	*x = ReturnReloadConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_return_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReturnReloadConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnReloadConfig) ProtoMessage() {}

func (x *ReturnReloadConfig) ProtoReflect() protoreflect.Message {
	mi := &file_return_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnReloadConfig.ProtoReflect.Descriptor instead.
func (*ReturnReloadConfig) Descriptor() ([]byte, []int) {
	return file_return_proto_rawDescGZIP(), []int{9}
}

type ReturnDiscard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReturnDiscard) Reset() {
	*x = ReturnDiscard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_return_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReturnDiscard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnDiscard) ProtoMessage() {}

func (x *ReturnDiscard) ProtoReflect() protoreflect.Message {
	mi := &file_return_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnDiscard.ProtoReflect.Descriptor instead.
func (*ReturnDiscard) Descriptor() ([]byte, []int) {
	return file_return_proto_rawDescGZIP(), []int{10}
}

var File_return_proto protoreflect.FileDescriptor

var file_return_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0b,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0b, 0x72, 0x65, 0x61,
	0x64, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x80, 0x05, 0x0a, 0x06, 0x52, 0x65, 0x74,
	0x75, 0x72, 0x6e, 0x12, 0x18, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x06, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x03, 0x65, 0x72, 0x72, 0x12, 0x48, 0x0a,
	0x15, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f,
	0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x52,
	0x65, 0x74, 0x75, 0x72, 0x6e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x52, 0x13, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x12, 0x2f, 0x0a, 0x0c, 0x6f, 0x66, 0x66, 0x65, 0x72,
	0x5f, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x52, 0x0b, 0x6f, 0x66, 0x66,
	0x65, 0x72, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x12, 0x42, 0x0a, 0x13, 0x6a, 0x6f, 0x69, 0x6e,
	0x5f, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x4a, 0x6f,
	0x69, 0x6e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x11, 0x6a, 0x6f, 0x69, 0x6e, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x12, 0x32, 0x0a, 0x0d,
	0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x5f, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x41, 0x6e, 0x73, 0x77,
	0x65, 0x72, 0x52, 0x0c, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e,
	0x12, 0x48, 0x0a, 0x15, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x5f, 0x61, 0x6e, 0x73, 0x77,
	0x65, 0x72, 0x5f, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x41,
	0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x13, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x41, 0x6e,
	0x73, 0x77, 0x65, 0x72, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x12, 0x2c, 0x0a, 0x0b, 0x73, 0x65,
	0x6e, 0x64, 0x5f, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0b, 0x2e, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x0a, 0x73, 0x65,
	0x6e, 0x64, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x12, 0x2f, 0x0a, 0x0c, 0x72, 0x65, 0x61, 0x64,
	0x79, 0x5f, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x52, 0x65, 0x61, 0x64, 0x79, 0x52, 0x0b, 0x72, 0x65,
	0x61, 0x64, 0x79, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x12, 0x42, 0x0a, 0x13, 0x64, 0x72, 0x6f,
	0x70, 0x5f, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x44,
	0x72, 0x6f, 0x70, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x11, 0x64, 0x72, 0x6f, 0x70,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x12, 0x45, 0x0a,
	0x14, 0x72, 0x65, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x72,
	0x65, 0x74, 0x75, 0x72, 0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x52, 0x65,
	0x74, 0x75, 0x72, 0x6e, 0x52, 0x65, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x52, 0x12, 0x72, 0x65, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65,
	0x74, 0x75, 0x72, 0x6e, 0x12, 0x35, 0x0a, 0x0e, 0x64, 0x69, 0x73, 0x63, 0x61, 0x72, 0x64, 0x5f,
	0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x52,
	0x65, 0x74, 0x75, 0x72, 0x6e, 0x44, 0x69, 0x73, 0x63, 0x61, 0x72, 0x64, 0x52, 0x0d, 0x64, 0x69,
	0x73, 0x63, 0x61, 0x72, 0x64, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x22, 0x15, 0x0a, 0x13, 0x52,
	0x65, 0x74, 0x75, 0x72, 0x6e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x22, 0x30, 0x0a, 0x0b, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x4f, 0x66, 0x66, 0x65,
	0x72, 0x12, 0x21, 0x0a, 0x0c, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x36,
	0x34, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x42, 0x61,
	0x73, 0x65, 0x36, 0x34, 0x22, 0x13, 0x0a, 0x11, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x4a, 0x6f,
	0x69, 0x6e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x33, 0x0a, 0x0c, 0x52, 0x65, 0x74,
	0x75, 0x72, 0x6e, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x23, 0x0a, 0x0d, 0x61, 0x6e, 0x73,
	0x77, 0x65, 0x72, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x36, 0x34, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x42, 0x61, 0x73, 0x65, 0x36, 0x34, 0x22, 0x15,
	0x0a, 0x13, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x41,
	0x6e, 0x73, 0x77, 0x65, 0x72, 0x22, 0x0c, 0x0a, 0x0a, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x53,
	0x65, 0x6e, 0x64, 0x22, 0x34, 0x0a, 0x0b, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x52, 0x65, 0x61,
	0x64, 0x79, 0x12, 0x25, 0x0a, 0x0a, 0x72, 0x65, 0x61, 0x64, 0x79, 0x5f, 0x6c, 0x69, 0x73, 0x74,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x79, 0x52, 0x09,
	0x72, 0x65, 0x61, 0x64, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x13, 0x0a, 0x11, 0x52, 0x65, 0x74,
	0x75, 0x72, 0x6e, 0x44, 0x72, 0x6f, 0x70, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x14,
	0x0a, 0x12, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x52, 0x65, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x22, 0x0f, 0x0a, 0x0d, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x44, 0x69,
	0x73, 0x63, 0x61, 0x72, 0x64, 0x42, 0x20, 0x5a, 0x1e, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x6d, 0x67, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x72, 0x65,
	0x74, 0x75, 0x72, 0x6e, 0x5f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_return_proto_rawDescOnce sync.Once
	file_return_proto_rawDescData = file_return_proto_rawDesc
)

func file_return_proto_rawDescGZIP() []byte {
	file_return_proto_rawDescOnce.Do(func() {
		file_return_proto_rawDescData = protoimpl.X.CompressGZIP(file_return_proto_rawDescData)
	})
	return file_return_proto_rawDescData
}

var file_return_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_return_proto_goTypes = []any{
	(*Return)(nil),              // 0: Return
	(*ReturnCreateSession)(nil), // 1: ReturnCreateSession
	(*ReturnOffer)(nil),         // 2: ReturnOffer
	(*ReturnJoinSession)(nil),   // 3: ReturnJoinSession
	(*ReturnAnswer)(nil),        // 4: ReturnAnswer
	(*ReturnConfirmAnswer)(nil), // 5: ReturnConfirmAnswer
	(*ReturnSend)(nil),          // 6: ReturnSend
	(*ReturnReady)(nil),         // 7: ReturnReady
	(*ReturnDropSession)(nil),   // 8: ReturnDropSession
	(*ReturnReloadConfig)(nil),  // 9: ReturnReloadConfig
	(*ReturnDiscard)(nil),       // 10: ReturnDiscard
	(*error_pb.Error)(nil),      // 11: Error
	(*ready_pb.Ready)(nil),      // 12: Ready
}
var file_return_proto_depIdxs = []int32{
	11, // 0: Return.err:type_name -> Error
	1,  // 1: Return.create_session_return:type_name -> ReturnCreateSession
	2,  // 2: Return.offer_return:type_name -> ReturnOffer
	3,  // 3: Return.join_session_return:type_name -> ReturnJoinSession
	4,  // 4: Return.answer_return:type_name -> ReturnAnswer
	5,  // 5: Return.confirm_answer_return:type_name -> ReturnConfirmAnswer
	6,  // 6: Return.send_return:type_name -> ReturnSend
	7,  // 7: Return.ready_return:type_name -> ReturnReady
	8,  // 8: Return.drop_session_return:type_name -> ReturnDropSession
	9,  // 9: Return.reload_config_return:type_name -> ReturnReloadConfig
	10, // 10: Return.discard_return:type_name -> ReturnDiscard
	12, // 11: ReturnReady.ready_list:type_name -> Ready
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_return_proto_init() }
func file_return_proto_init() {
	if File_return_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_return_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Return); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_return_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ReturnCreateSession); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_return_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ReturnOffer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_return_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ReturnJoinSession); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_return_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*ReturnAnswer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_return_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*ReturnConfirmAnswer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_return_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*ReturnSend); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_return_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*ReturnReady); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_return_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*ReturnDropSession); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_return_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*ReturnReloadConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_return_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*ReturnDiscard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_return_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_return_proto_goTypes,
		DependencyIndexes: file_return_proto_depIdxs,
		MessageInfos:      file_return_proto_msgTypes,
	}.Build()
	File_return_proto = out.File
	file_return_proto_rawDesc = nil
	file_return_proto_goTypes = nil
	file_return_proto_depIdxs = nil
}
